server:
  port: 8081

spring:
  application:
    name: notification-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

aws:
  dynamodb:
    endpoint: http://localhost:8001
    region: us-east-1
    access-key: dummy
    secret-key: dummy
